### ISSUE TITLE
Add copilot-setup-steps.yml for Copilot agent pre-setup in CI

### ISSUE THREAD

**Issue by DanielAvdar** [DanielAvdar/tabnet#101]
This PR adds a new workflow file, .github/workflows/copilot-setup-steps.yml, which pre-configures the environment for the Copilot agent before firewall restrictions are enabled. This workflow matches the main CI setup: it checks out the code, sets up uv, installs Python 3.11, and runs make to pre-build the project. This ensures all dependencies are fetched and built before the Copilot agent starts, preventing firewall-related errors during dependency download or setup steps.

```yaml name=.github/workflows/copilot-setup-steps.yml
name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python 3.11
        run: uv python install 3.11

      - name: Pre-build project
        run: make
```

This workflow can be manually triggered via the Actions tab for testing. Please review and suggest any additional environment setup steps if needed.
